services:
    server:
        build: ./
        image: spendwiser-server
        container_name: spendwiser-server
        restart: unless-stopped
        expose:
            - "3000:3000"
        volumes:
            - .:/usr/src/server
            - ./node_modules:/usr/src/server/node_modules
        depends_on:
            - database
        networks:
            - server-bridge
    database:
        image: mongo
        container_name: mongo-db
        restart: unless-stopped
        expose:
            - "27017:27017"
        volumes:
            - ./database:/data/db
        networks:
            - server-bridge
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./nginx/nginx-dev.conf:/etc/nginx/nginx.conf"
            - "./cert:/etc/nginx/ssl"
        depends_on:
            - server
        networks:
            - server-bridge
networks:
    server-bridge:
        driver: bridge