services:
    server:
        build: ./
        image: spendwiser-server
        container_name: spendwiser-server
        restart: unless-stopped
        volumes:
            - ".:/usr/src/server"
        ports:
            - "3000:3000"
        depends_on:
            - database
        networks:
            - server-bridge
        environment:
            - "LOAD_FILE=${LOAD_FILE}"
            - "MONGO_DEFAULT_DB=${MONGO_DEFAULT_DB}"
            - "AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}"
            - "AUTH0_DOMAIN=${AUTH0_DOMAIN}"
            - "AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}"
            - "ADMIN_JSON=${ADMIN_JSON}"
    database:
        image: mongo
        container_name: mongo-db
        restart: unless-stopped
        expose:
            - "27017"
        volumes:
            - ${DB_LOCATION}:/data/db
        networks:
            - server-bridge
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
            - "${SSL_CERT}:/etc/nginx/ssl/cert.pem"
            - "${SSL_KEY}:/etc/nginx/ssl/key.pem"
        depends_on:
            - server
        networks:
            - server-bridge
        environment:
            - "SERVER_HOST=${SERVER_HOST}"
networks:
    server-bridge:
        driver: bridge