services:
    server:
        build: ./
        image: spendwiser-server
        container_name: spendwiser-server
        restart: unless-stopped
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/server
            - ./node_modules:/usr/src/server/node_modules
        depends_on:
            - database
        networks:
            - server-bridge
    database:
        image: mongo
        container_name: mongo-db
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - ./database:/data/db
        networks:
            - server-bridge
networks:
    server-bridge:
        driver: bridge